# 应用配置
spring.application.name=issue2md

# Gitee API 配置
gitee.token=c8d06a4c481f23f10c62cc2eb7b3fd48
gitee.base-url=https://gitee.com/api/v5
gitee.comments-max-count=50

# 输出配置
output.default-dir=./output